name: Java CI with Maven

on:
  pull_request:
    branches: 
      - main
    types: [opened]
    
  workflow_dispatch:

jobs:
  build_if_merged:
  
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Clone project to WORKSPACE
      uses: actions/checkout@v3
    - run: ls -la

    - name: Install Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'
    - run: java -version

    - name: Run tests
      run: mvn clean test

    - name: Build project
      run: mvn clean package -Dmaven.test.skip=true 

    - name: Show packaged in target
      run: ls -la ./target      
